app:
  tokenEnv: APP_TOKEN

client:
  protocolVersion: 772
  timeout: 7000

database:
  url: jdbc:mariadb://localhost:3306/azisababot
  usernameEnv: DATABASE_USERNAME
  passwordEnv: DATABASE_PASSWORD
  maxPoolSize: 10

locale: ja-JP